name: "apparel_dbt"
version: "1.0.0"
config-version: 2

profile: "apparel_dbt"

model-paths: ["models"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
test-paths: ["tests"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  apparel_dbt:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: incremental
      +incremental_strategy: merge
      +schema: analytics
